# Generated by Django 5.0.4 on 2024-05-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_chores_backend_server', '0002_rename_group_chore_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groceryphoto',
            old_name='grocery_id',
            new_name='grocery',
        ),
    ]
