# Generated by Django 5.0.4 on 2024-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_chores_backend_server', '0003_rename_group_id_chore_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
