# Generated by Django 5.0.4 on 2024-05-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_chores_backend_server', '0004_alter_grocery_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='chore',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
