# Generated by Django 5.0.4 on 2024-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_chores_backend_server', '0005_remove_chore_due_date_alter_chore_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
