# Generated by Django 5.0.4 on 2024-05-15 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_chores_backend_server', '0007_alter_chore_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chore',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
